"""Init

Revision ID: c121e5468799
Revises: b328929bf4ff
Create Date: 2024-05-06 21:02:01.102090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c121e5468799'
down_revision: Union[str, None] = 'b328929bf4ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('students', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'students', 'groups', ['group_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'group_id')
    op.drop_table('groups')
    # ### end Alembic commands ###
